spring:
  application:
    name: mqtt-mysql-service
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  insert:
    batch-size: 500      # 增加批量大小，提高写入性能
    batch-interval-ms: 200  # 减少间隔时间，提高实时性
  retention:
    message-days: 7      # 消息保留7天
    message-detail-days: 3  # 消息明细保留3天