spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mqttlistener?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
