spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mqttlistener?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 20
      # 连接池最小空闲连接数
      minimum-idle: 5
      # 连接超时时间
      connection-timeout: 30000
      # 空闲连接存活最大时间
      idle-timeout: 600000
      # 连接最大存活时间
      max-lifetime: 1800000
      # 连接测试查询
      connection-test-query: SELECT 1
      # 批量插入优化
      data-source-properties:
        rewriteBatchedStatements: true
        useServerPrepStmts: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048


